config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */
use Cake\Http\Middleware\CsrfProtectionMiddleware;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 * Cache: Routes are cached to improve performance, check the RoutingMiddleware
 * constructor in your `src/Application.php` file to change this behavior.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {
    // Register scoped middleware for in scopes.
    $routes->registerMiddleware('csrf', new CsrfProtectionMiddleware([
        'httpOnly' => true
    ]));

    /**
     * Apply a middleware to the current route scope.
     * Requires middleware to be registered via `Application::routes()` with `registerMiddleware()`
     */
    $routes->applyMiddleware('csrf');

    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'Pages', 'action' => 'index']);
    $routes->connect('/logout', ['controller' => 'Pages', 'action' => 'logout']);
    $routes->connect('/edit-profile', ['controller' => 'Pages', 'action' => 'edit-profile']);
    
    $routes->fallbacks(DashedRoute::class);
});

/**
 * If you need a different set of middleware or none at all,
 * open new scope and define routes there.
 *
 * ```
 * Router::scope('/api', function (RouteBuilder $routes) {
 *     // No $routes->applyMiddleware() here.
 *     // Connect API actions here.
 * });
 * ```
 */

src/Model/Table/PickingListsTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * PickingLists Model
 *
 * @property \App\Model\Table\CustomersTable|\Cake\ORM\Association\BelongsTo $Customers
 * @property \App\Model\Table\ExpendituresPickingListsDetailsTable|\Cake\ORM\Association\HasMany $ExpendituresPickingListsDetails
 * @property \App\Model\Table\PickingListsDetailsTable|\Cake\ORM\Association\HasMany $PickingListsDetails
 * @property \App\Model\Table\ExpendituresTable|\Cake\ORM\Association\BelongsToMany $Expenditures
 *
 * @method \App\Model\Entity\PickingList get($primaryKey, $options = [])
 * @method \App\Model\Entity\PickingList newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\PickingList[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\PickingList|bool save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\PickingList|bool saveOrFail(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\PickingList patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\PickingList[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\PickingList findOrCreate($search, callable $callback = null, $options = [])
 *
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 */
class PickingListsTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('picking_lists');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');

        $this->addBehavior('Timestamp');

        $this->belongsTo('Customers', [
            'foreignKey' => 'customer_id',
            'joinType' => 'INNER'
        ]);
        $this->hasMany('ExpendituresPickingListsDetails', [
            'foreignKey' => 'picking_list_id'
        ]);
        $this->hasMany('PickingListsDetails', [
            'foreignKey' => 'picking_list_id',
            'dependent' => true,
            'cascadeCallbacks' => true,
        ]);
        $this->belongsToMany('Expenditures', [
            'foreignKey' => 'picking_list_id',
            'targetForeignKey' => 'expenditure_id',
            'joinTable' => 'expenditures_picking_lists'
        ]);

        $this->belongsTo('CreatedUsers', [
            'foreignKey' => 'created_by',
            'className'=>'Users'
        ]);
        $this->belongsTo('ModifiedUsers', [
            'foreignKey' => 'modified_by',
            'className'=>'Users'
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->allowEmptyString('id', 'create');

        $validator
            ->scalar('code')
            ->maxLength('code', 225)
            ->allowEmptyString('code');

        $validator
            ->date('date')
            ->requirePresence('date', 'create')
            ->allowEmptyDate('date', false);

        $validator
            ->integer('created_by')
            ->allowEmptyString('created_by');

        $validator
            ->integer('modified_by')
            ->allowEmptyString('modified_by');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->existsIn(['customer_id'], 'Customers'));

        return $rules;
    }

    public function beforeSave(\Cake\Event\Event $event, \Cake\ORM\Entity $entity, 
    \ArrayObject $options)
    {
        if($entity->isNew()){
            $date       = $entity->date->format('Y-m-d');
            $year       = substr($date,0,4);
            $month      = substr($date,5,2);
            
            $getLastCode = $this->find()->select([
                'codeNum'=>'(CAST(SUBSTR(`code`,12,5) AS UNSIGNED) )'
            ])
            ->where([
                'YEAR(date)'    => $year,
                'MONTH(date)'   => $month 
            ])
            ->order('codeNum DESC')
            ->first();
            if(!empty($getLastCode)){
                $lastCode = $getLastCode->codeNum;
            }else{
                $lastCode = 0;
            }
            $lastCode       = $lastCode +1;
            $entity->code   = "PL.".$year.".".$month.".".str_pad($lastCode,5,0,STR_PAD_LEFT);
        }
        return true;
    }
}

src/Controller/PickingListsController.php
<?php
namespace App\Controller;

use App\Controller\AppController;
use Cake\Event\Event;
use Cake\Routing\Router;
/**
 * PickingLists Controller
 *
 * @property \App\Model\Table\PickingListsTable $PickingLists
 *
 * @method \App\Model\Entity\Currency[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class PickingListsController extends AppController
{

    private $titleModule = "Picking List";
    private $primaryModel = "PickingLists";


    public function initialize()
    {
        parent::initialize();
        $this->Auth->allow(['configure']);
        $this->set([
            'titleModule' => $this->titleModule,
            'primaryModel' => $this->primaryModel,
        ]);
    }

    function beforeFilter(\Cake\Event\Event $event){
        parent::beforeFilter($event);
    
            $this->Security->config('validatePost',false);
            //$this->getEventManager()->off($this->Csrf);
    }

    /**
     * Index method
     *
     * @return \Cake\Http\Response|void
     */
    public function index()
    {
        if($this->request->is('ajax')){
            $source = $this->{$this->primaryModel};
            $searchAble = [
                $this->primaryModel.'.id',
                $this->primaryModel.'.name'
            ];
            $data = [
                'source'=>$source,
                'searchAble' => $searchAble,
                'defaultField' => $this->primaryModel.'.id',
                'defaultSort' => 'desc',
                'contain' => [
                    'Customers'
                ]
                    
            ];
            $dataTable   = $this->Datatables->make($data);  
            $this->set('aaData',$dataTable['aaData']);
            $this->set('iTotalDisplayRecords',$dataTable['iTotalDisplayRecords']);
            $this->set('iTotalRecords',$dataTable['iTotalRecords']);
            $this->set('sColumns',$dataTable['sColumns']);
            $this->set('sEcho',$dataTable['sEcho']);
            $this->set('_serialize',['aaData','iTotalDisplayRecords','iTotalRecords','sColumns','sEcho']);
        }else{
            $titlesubModule = "List ".$this->titleModule;
            $breadCrumbs = [
                Router::url(['action' => 'index']) => $titlesubModule
            ];
            $this->set(compact('breadCrumbs','titlesubModule'));
        }
        
        
    }

    /**
     * View method
     *
     * @param string|null $id Country id.
     * @return \Cake\Http\Response|void
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null)
    {
        $record = $this->{$this->primaryModel}->get($id, [
            'contain' => [
                'CreatedUsers',
                'Customers',
                'PickingListsDetails',
                'PickingListsDetails.VwStocksLocations'
            ]
        ]);
        $this->set('record', $record);
        $this->set('_serialize',['record']);
        $titlesubModule = "View ".$this->titleModule;
        $breadCrumbs = [
            Router::url(['action' => 'index']) => "List ".$this->titleModule,
            Router::url(['action' => 'view',$id]) => $titlesubModule
        ];
        $this->set(compact('breadCrumbs','titlesubModule'));
        $this->layout = false;
    }

    /**
     * Add method
     *
     * @return \Cake\Http\Response|null Redirects on successful add, renders view otherwise.
     */
    public function add()
    {
        $record = $this->{$this->primaryModel}->newEntity();
        if ($this->request->is('post')) {
            $data = $this->request->getData();
            $data['date'] = $this->Utilities->generalitationDateFormat($data['date']);
            $data['status'] = 0;
            foreach($data['picking_lists_details'] as $key => $ptd){
                if(empty($ptd['stocks_location_id'])){
                    unset($data['picking_lists_details'][$key]);
                }
            }
            $record = $this->{$this->primaryModel}->patchEntity($record, $data);
            if ($this->{$this->primaryModel}->save($record)) {
                $this->Flash->success(__($this->Utilities->message_alert($this->titleModule,1)));
                $status = "SUCCESS";
                $message = "DATA BERHASIL DISIMPAN";
                $code   = 200;
                $errors = [];
            }else{
                $status = "ERROR";
                $message = "DATA GAGAL DISIMPAN";
                $code   = 50;
                $errors = call_user_func_array('array_merge', $record->errors());
            }
            $this->set(compact('status','code','message','errors'));
            $this->set('_serialize',['status','code','message','errors']);
            // $this->Flash->error(__($this->Utilities->message_alert($this->titleModule,2)));
        }
        $this->loadModel('VwStocksLocations');
        $this->loadModel('StocksLocations');
        $stocksLocations = $this->VwStocksLocations->find()
        ->select($this->VwStocksLocations)
        ->select([
            'StocksLocationTemporaryStock' => '(`StocksLocationActualStock`) - ('.
                $this->{$this->primaryModel}->PickingListsDetails->find()->select([
                    'PTDQTY' => '(IFNULL(SUM(`PickingListsDetails`.`qty`),0))' 
                ])->where([
                    '`PickingListsDetails`.`stocks_location_id` = VwStocksLocations.StocksLocationID'
                ])
            .')'
        ])
        ->order([
            '`VwStocksLocations`.`RDate`' => 'ASC',
        ])->having([
            '`StocksLocationTemporaryStock` >' => 0
        ]);
        $customers = $this->{$this->primaryModel}->Customers->find('list')
                    ->order([
                        'Customers.name' => 'ASC'
                    ]);
        $this->set(compact('record','stocksLocations','customers'));
        $titlesubModule = "Tambah ".$this->titleModule;
        $breadCrumbs = [
            Router::url(['action' => 'index']) => "List ".$this->titleModule,
            Router::url(['action' => 'add']) => $titlesubModule
        ];
        $this->set(compact('breadCrumbs','titlesubModule'));
    }

    /**
     * Edit method
     *
     * @param string|null $id Country id.
     * @return \Cake\Http\Response|null Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit($id = null)
    {
        $record = $this->{$this->primaryModel}->get($id, [
            'contain' => [
                
            ]
        ]);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $ptdOldId = [];
            $data = $this->request->getData();
            $data['date'] = $this->Utilities->generalitationDateFormat($data['date']);
            foreach($data['picking_lists_details'] as $key => $ptd){
                if(empty($ptd['stock_id'])){
                    unset($data['picking_lists_details'][$key]);
                    if(!empty($ptd['id'])){
                        array_push($ptdOldId,$ptd['id']);
                    }
                }
            }
            $record = $this->{$this->primaryModel}->patchEntity($record, $data);
            if (empty($record->errors())) {
                foreach($ptdOldId as $key => $idPtd){
                   $ptd = $this->{$this->primaryModel}->PickingListsDetails->get($idPtd);
                   $this->{$this->primaryModel}->PickingListsDetails->delete($ptd);
                }
                $this->{$this->primaryModel}->save($record);
                $this->Flash->success(__($this->Utilities->message_alert($this->titleModule,3)));
                $status = "SUCCESS";
                $message = "DATA BERHASIL DISIMPAN";
                $code   = 200;
                $errors = [];
            }else{
                $status = "ERROR";
                $message = "DATA GAGAL DISIMPAN";
                $code   = 50;
                $errors = call_user_func_array('array_merge', $record->errors());
            }
            $this->set(compact('status','code','message','errors'));
            $this->set('_serialize',['status','code','message','errors']);
        }
        $this->loadModel('VwStocksLocations');
        $this->loadModel('StocksLocations');
        $stocksLocations = $this->VwStocksLocations->find()
        ->select($this->VwStocksLocations)
        ->order([
            '`VwStocksLocations`.`RDate`' => 'ASC',
        ])->having([
            '`VwStocksLocations`.`StocksLocationActualStock` >' => 0
        ]);
        $customers = $this->{$this->primaryModel}->Customers->find('list')
                    ->order([
                        'Customers.name' => 'ASC'
                    ]);
        $record->date = $record->date->format('d-m-Y');
        $this->set(compact('record','stocksLocations','customers'));
        $titlesubModule = "Edit ".$this->titleModule;
        $breadCrumbs = [
            Router::url(['action' => 'index']) => "List ".$this->titleModule,
            Router::url(['action' => 'edit',$id]) => $titlesubModule
        ];
        $this->set(compact('breadCrumbs','titlesubModule'));
    }

    /**
     * Delete method
     *
     * @param string|null $id Country id.
     * @return \Cake\Http\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $record = $this->{$this->primaryModel}->get($id);
        if ($this->{$this->primaryModel}->delete($record)) {
            $code = 200;
            $message = __($this->Utilities->message_alert($this->titleModule,5));
            $status = 'success';
        } else {
            $code = 99;
            $message = __($this->Utilities->message_alert($this->titleModule,6));
            $status = 'error';
        }

src/Template/PickingLists/add.ctp
<?php
    $this->start('sub_header_toolbar');
?>
    <?php if($this->Acl->check(['action'=>'index']) == true):?>
        <a href="<?=$this->Url->build(['action'=>'index']);?>" class="btn btn-warning">
            <i class="la la-angle-double-left"></i> Kembali
        </a>
    <?php endif;?>
<?php
    $this->end();
?>
<div class="row">
    <div class="col-md-12">
        <div class="kt-portlet">
            <div class="kt-portlet__head">
				<div class="kt-portlet__head-label">
					<h3 class="kt-portlet__head-title">
						<?=$titlesubModule;?>
					</h3>
				</div>
			</div>
			<!--begin::Form-->
			<?= $this->Form->create($record,['class'=>'kt-form','type'=>'file']) ?>
				<div class="kt-portlet__body">
					<div class="kt-section kt-section--first">
                        <div class="row">
                            <div class="col-md-6">
                                <?=$this->Form->control('date',[
                                    'class'=>'form-control m-input date-picker',
                                    'type' => 'text',
                                    'value'=> date('d-m-Y'),
                                    'autocomplete' => 'off',
                                    'templateVars' => [
                                        'colsize' => 'col-lg-8 col-md-7',
                                    ],
                                    'label' => [
                                        'class'=> 'col-lg-4 col-md-5 col-form-label',
                                        'text'=>'TGL. PICKING LIST*'
                                    ],
                                ]);?>
                            </div>
                            <div class="col-md-6">
                                <?=$this->Form->control('customer_id',[
                                    'class'=>'form-control m-input',
                                    'empty' => 'PILIH CUSTOOMER',
                                    'templateVars' => [
                                        'colsize' => 'col-lg-8 col-md-7',
                                    ],
                                    'label' => [
                                        'class'=> 'col-lg-4 col-md-5 col-form-label',
                                        'text'=>'CUSTOMER *'
                                    ],
                                ]);?>
                            </div>
                        </div>
		            </div>
                    <div class="kt-section kt-section--last">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="table-responsive">
                                    <table class="table table-sm table-bordered table-input">
                                        <thead>
                                            <tr>
                                                <th width="50px" class="text-center">
                                                    <label class="kt-checkbox kt-checkbox--tick kt-checkbox--brand">
                                                        <input type="checkbox" class="checkall">
                                                        <span></span>
                                                    </label>
                                                </th>
                                                <th width="10%">NO. PENERIMAAN</th>
                                                <th width="10%">TGL. PENERIMAAN</th>
                                                <th width="10%">NO. PENGAJUAN</th>
                                                <th width="10%">LOKASI</th>
                                                <th>NAMA BARANG</th>
                                                <th width="10%">SATUAN</th>
                                                <th width="10%">SALDO</th>
                                                <th width="10%">QTY</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php foreach($stocksLocations as $key => $stockLocation):?>
                                                <tr class="tr-input">
                                                    <td class="text-center">
                                                        <input type="hidden" class="hiddenid" value="0" name="picking_lists_details[<?=$key;?>][stocks_location_id]">
                                                        <label class="kt-checkbox kt-checkbox--tick kt-checkbox--brand">
                                                            <input type="checkbox" class="checkid" value="<?=$stockLocation->StocksLocationID;?>" name="picking_lists_details[<?=$key;?>][stocks_location_id]">
                                                            <span></span>
                                                        </label>
                                                    </td>
                                                    <td><?=$stockLocation->RCode;?></td>
                                                    <td><?=$stockLocation->RDate->format('d-m-Y');?></td>
                                                    <td><?=$stockLocation->RBCCode;?></td>
                                                    <td><?=$stockLocation->LocationName;?></td>
                                                    <td><?=$stockLocation->ProductName;?></td>
                                                    <td><?=$stockLocation->ProductUnit;?></td>
                                                    <td class="text-right"><?=number_format($stockLocation->StocksLocationTemporaryStock,2);?></td>
                                                    <td class="td-input">
                                                        <input type="text" value="<?=$stockLocation->StocksLocationTemporaryStock;?>" class="form-control m-input onlyNumber" name="picking_lists_details[<?=$key;?>][qty]">
                                                    </td>
                                                </tr>
                                            <?php endforeach;?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
	            </div>
	            <div class="kt-portlet__foot">
					<div class="kt-form__actions">
						<div class="row">
							<div class="col-lg-12">
                                <button type="submit" class="btn btn-primary btn-submit">Submit</button>
								<button type="reset" class="btn btn-warning">Reset</button>
							</div>
						</div>
					</div>
				</div>
			<?=$this->Form->end();?>
			<!--end::Form-->
		</div>
    </div>
</div>

<?php $this->start('script');?>
    <script>
        $("#customer-id").select2({});
        $(".checkall").on("click",function(e){
            if($(this).prop("checked")){
                $(".checkid").prop("checked",true);
            }else{
                $(".checkid").prop("checked",false);
            }
        })

        var form = $('.kt-form');
        

        form.submit(function (e) {
			e.preventDefault();
            var btn = $('.btn-submit');
            var rulesValidate = {
                date: {
                    required: true
                },
                location_id: {
                    required: true
                },
            };

            form.validate({
                rules: rulesValidate,
            });

			if (!form.valid()) {
				return;
			}

			btn.addClass('kt-loader kt-loader--right kt-loader--light').attr('disabled', true);
            KTApp.block($("#kt_wrapper"))

			form.ajaxSubmit({
                dataType : 'json',
                beforeSend : function(){
                },
				success: function (response, status, xhr, $form) {
                    KTApp.unblock($("#kt_wrapper"))
                    btn.removeClass('kt-loader kt-loader--right kt-loader--light').attr('disabled', false);
                    if(response.code == 200){
                        window.location.href='<?=$this->Url->build(['action'=>'index']);?>'
                    }else{
                        Utils.showAlertMsg(form, 'danger', response.message,response.errors);
                        KTUtil.scrollTo("kt_wrapper",-200)
                    }
                    
                },
                error : function(){
                    KTApp.unblock($("#kt_wrapper"))
                    Utils.showAlertMsg(form, 'danger', 'GAGAL DISIMPAN',[]);
                    KTUtil.scrollTo("kt_wrapper",-200)
                }
			});
		});
    </script>
<?php $this->end();?>

src/Template/PickingLists/view.ctp
<html>
    <head>
        <meta charset="utf-8"/>
        <title><?=$defaultAppSettings['App.Name'];?><?=(!empty($titleModule) ? ' | '.$titleModule : '');?></title>
        <style>
            html,body{
                padding:5px;
                margin:0px;
                font-family:sans-serif;
            }
            table{
                font-size:11px;
                line-height:1.3;
                border-collapse: collapse;
                width:100%;
            }
            .table-header{
                margin-bottom:15px;
            }
            .table-main{
                border-top:4px double #000;
                border-bottom:4px double #000;
            }
            .table-main th{
                vertical-align:top;
            }
            .table-header th,.table-main th{
                text-align:left;
            }
            .company-name{
                font-size:14px;
            }
            .document-type{
                border: 2px solid #000;
                padding:5px;
                text-align:center;
            }
            .document-name{
                border-bottom: 1px solid #000;
                
            }
            .table-content{
                margin-top:10px;
                border:1px solid #000;
            }
            .table-content th,.table-content td{
                border-right:1px solid #000;
                border-bottom:1px solid #000;
            }
            .table-content td{
                vertical-align:top;
            }

            .text-center{
                text-align:center;
            }
            .text-right{
                text-align:right;
            }
            .table-signature{
                width:400px;
                margin-top:15px;
                text-align:center;
            }
        </style>
    </head>
    <body>
        <table class="table-header">
            <thead>
                <tr>
                    <th width="400px">
                        <div class="company-name"><?=$defaultAppSettings['Company.Name'];?></div>
                        <div class="company-address"><?=$defaultAppSettings['Company.Address'];?></div>
                    </th>
                    <th></th>
                    <th width="150px">
                        <div class="document-type">
                            <div class="document-name">PICKING LIST</div>
                            <div class="document-code"><?=$record->code;?></div>
                        </div>
                    </th>
                </tr>
            </thead>
        </table>
        <table class="table-main">
            <tbody>
                <tr>
                    <th width="15%">TANGGAL PICKING LIST</th>
                    <th width="2%">:</th>
                    <th width=""><?=$record->date->format('d-m-Y');?></th>
                </tr>
                <tr>
                    <th>CUSTOMER</th>
                    <th>:</th>
                    <th>
                        <?=$record->customer->name;?>
                    </th>
                </tr>
            </tbody>
        </table>
        <table class="table-content">
            <thead>
                <tr>
                    <th width="10%">NO. PENERIMAAN</th>
                    <th width="10%">TGL. PENERIMAAN</th>
                    <th width="10%">NO. PENGAJUAN</th>
                    <th width="10%">LOKASI</th>
                    <th>NAMA BARANG</th>
                    <th width="10%">SATUAN</th>
                    <th width="10%">QTY</th>
                </tr>
            </thead>
            <tbody>
                <?php $totalQty = 0;?>
                <?php foreach($record->picking_lists_details as $key => $pickingListsDetail):?>
                    <?php $stockLocation = $pickingListsDetail->vw_stocks_location;?>
                    <tr>
                        <td><?=$stockLocation->RCode;?></td>
                        <td><?=$stockLocation->RDate->format('d-m-Y');?></td>
                        <td><?=$stockLocation->RBCCode;?></td>
                        <td><?=$stockLocation->LocationName;?></td>
                        <td><?=$stockLocation->ProductName;?></td>
                        <td><?=$stockLocation->ProductUnit;?></td>
                        <td class="text-right"><?=number_format($pickingListsDetail->qty,2);?></td>
                    </tr>
                <?php endforeach;?>
            </tbody>
        </table>
        <table class="table-signature">
            <tbody>
                <tr>
                    <td width="50%">
                        USER PEMBUAT<br><br><br><br>
                        (<?=$record->created_user->name;?>)
                    </td>
                    <td width="50%">
                        MENGETAHUI<br><br><br><br>
                        (..................................)
                    </td>
                </tr>
            </tbody>
        </table>
    </body>
</html>